version: '2.2'

services:
  drupal:
    image: drupal
    ports: 
        - "8080:80"
    volumes: 
        - /var/www/html/modules
        - /var/www/html/profiles
        - /var/www/html/sites
        - /var/www/html/themes
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=mypassword
volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: